USE AstroLearnDB;
GO

CREATE TABLE Users (
    UserID INT IDENTITY(1,1) PRIMARY KEY,
    Username NVARCHAR(50) NOT NULL UNIQUE,
    Email NVARCHAR(100) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(256) NOT NULL,
    Role NVARCHAR(20) NOT NULL DEFAULT 'Member',
    DateCreated DATETIME NOT NULL DEFAULT GETDATE()
);
GO

CREATE TABLE Profiles (
    ProfileID INT IDENTITY(1,1) PRIMARY KEY,
    UserID INT NOT NULL UNIQUE
        REFERENCES Users(UserID) ON DELETE CASCADE,
    FullName NVARCHAR(100) NULL,
    ProgressPct INT NOT NULL DEFAULT 0
);
GO

CREATE TABLE Lessons (
    LessonID INT IDENTITY(1,1) PRIMARY KEY,
    Title NVARCHAR(150) NOT NULL,
    Topic NVARCHAR(50) NOT NULL,
    Content NVARCHAR(MAX) NOT NULL,
    ImageUrl NVARCHAR(255) NULL,
    AdminID INT NOT NULL REFERENCES Users(UserID),
    DateCreated DATETIME NOT NULL DEFAULT GETDATE()
);
GO

CREATE TABLE Quizzes (
    QuizID INT IDENTITY(1,1) PRIMARY KEY,
    LessonID INT NOT NULL
        REFERENCES Lessons(LessonID) ON DELETE CASCADE,
    Question NVARCHAR(300) NOT NULL,
    OptionA NVARCHAR(150) NOT NULL,
    OptionB NVARCHAR(150) NOT NULL,
    OptionC NVARCHAR(150) NOT NULL,
    OptionD NVARCHAR(150) NOT NULL,
    CorrectOption CHAR(1) NOT NULL
        CHECK (CorrectOption IN ('A','B','C','D'))
);
GO

CREATE TABLE QuizResults (
    ResultID INT IDENTITY(1,1) PRIMARY KEY,
    UserID INT NOT NULL
        REFERENCES Users(UserID) ON DELETE CASCADE,
    LessonID INT NOT NULL
        REFERENCES Lessons(LessonID),
    Score INT NOT NULL,
    TotalQuestions INT NOT NULL,
    DateTaken DATETIME NOT NULL DEFAULT GETDATE()
);
GO

CREATE TABLE Simulations (
    SimID INT IDENTITY(1,1) PRIMARY KEY,
    LessonID INT NULL REFERENCES Lessons(LessonID),
    Title NVARCHAR(150) NOT NULL,
    Description NVARCHAR(400) NULL,
    AssetUrl NVARCHAR(255) NULL
);
GO

CREATE TABLE Discussions (
    PostID INT IDENTITY(1,1) PRIMARY KEY,
    UserID INT NOT NULL
        REFERENCES Users(UserID) ON DELETE CASCADE,
    LessonID INT NOT NULL
        REFERENCES Lessons(LessonID),
    Message NVARCHAR(1000) NOT NULL,
    DatePosted DATETIME NOT NULL DEFAULT GETDATE()
);
GO

CREATE TABLE Announcements (
    AnnouncementID INT IDENTITY(1,1) PRIMARY KEY,
    Title NVARCHAR(150) NOT NULL,
    Body NVARCHAR(1000) NOT NULL,
    AdminID INT NOT NULL REFERENCES Users(UserID),
    DatePosted DATETIME NOT NULL DEFAULT GETDATE()
);
GO